### ISSUE TITLE
Doesn't open

### ISSUE THREAD

**Issue by udoschmitz** [DenBeke/YouTube-Downloader-for-macOS#13]
YouTube Downloader Beta 0.9, MacOS 12.5 (21G72).

Doesn't open, when I try to delete the app Finder says it is still open, doesn't show up in dock or Force Quit dialog.

**Comment by DenBeke** [comment]
The application doesn't have an icon in the dock. The icon is located in the top right status bar. There you can simply click on the "Quit" button.
