### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by mirozahorak** [DenBeke/YouTube-Downloader-for-macOS#20]
trying to download f.e. https://www.youtube.com/watch?v=QS3XtFoFN1I
it is probably related to this bug:
https://github.com/yt-dlp/yt-dlp/issues/6247

I get this message:
WARNING: [youtube] QS3XtFoFN1I: nsig extraction failed: You may experience throttling for some formats
Install PhantomJS to workaround the issue
n = nbe8Lu4QmloK9QrU ; player = https://www.youtube.com/s/player/11e3a4ec/player_ias.vflset/en_US/base.js
ERROR: [youtube] QS3XtFoFN1I: Unable to extract uploader id; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

**Comment by DenBeke** [comment]
Fixed it in the latest version.  
Thank you for reporting the issue.
