### ISSUE TITLE
Can't download anymore

### ISSUE THREAD

**Issue by frranck** [DenBeke/YouTube-Downloader-for-macOS#24]
Hello Mathias, 
It broke a couple of days ago and can't download anything.
I really liked your software, it's simple and nice.
Any chance for fix?
Regards
Franck

**Comment by DenBeke** [comment]
Fixed it: https://github.com/DenBeke/YouTube-Downloader-for-macOS/releases/tag/v0.13

Thanks for notifying me!

**Comment by frranck** [comment]
Working perfect, thanks
