### ISSUE TITLE
Version 0.13 contains ARM-only binary

### ISSUE THREAD

**Issue by suschizu** [DenBeke/YouTube-Downloader-for-macOS#25]
the download contains an arm-only binary - intentional?

<img width="308" alt="Screenshot 2024-07-16 at 22 07 06" src="https://github.com/user-attachments/assets/ac0e8f9c-1811-40a3-917c-5be73f179b17">

**Comment by DenBeke** [comment]
Not at all, this should have been universal but apparently Xcode didn't do it out the box anymore.

I created a new and fixed release with a universal binary: https://github.com/DenBeke/YouTube-Downloader-for-macOS/releases/tag/v0.14

**Comment by suschizu** [comment]
great thanks for the quick fix! I can confirm that version 0.14 contains an universal build 🙌
