### ISSUE TITLE
Oops, something went wrong on certain videos

### ISSUE THREAD

**Issue by frranck** [DenBeke/YouTube-Downloader-for-macOS#26]
Hello,
Sometime I'm having this error:

`WARNING: [youtube] JqZx-jHEjOA: nsig extraction failed: Some formats may be missing
n = Uu-SNZqlWDrVpzAz6c ; player = https://www.youtube.com/s/player/3400486c/player_ias.vflset/en_US/base.js
WARNING: [youtube] JqZx-jHEjOA: nsig extraction failed: Some formats may be missing
n = ClSlkwE-n2n1KaFFj0 ; player = https://www.youtube.com/s/player/3400486c/player_ias.vflset/en_US/base.js
ERROR: [youtube] JqZx-jHEjOA: Requested format is not available. Use --list-formats for a list of available formats`

For example on this video https://www.youtube.com/watch?v=JqZx-jHEjOA

**Comment by yassiiin** [comment]
Receiving the same error recently

**Comment by frranck** [comment]
Yeah seems to be on any video actually.

**Comment by DenBeke** [comment]
It seems that something changed at youtube's end...
I updated yt-dlp yet again, and it seems to fix the problem: https://github.com/DenBeke/YouTube-Downloader-for-macOS/releases/tag/v0.15

Could you check again?

**Comment by yassiiin** [comment]
Works again, thanks :)
