### ISSUE TITLE
broken format error (poToken)

### ISSUE THREAD

**Issue by frranck** [DenBeke/YouTube-Downloader-for-macOS#27]
Hello,
I'm having his error:
<img width="513" alt="Screenshot 2024-08-01 at 08 54 16" src="https://github.com/user-attachments/assets/653b0375-a453-4e40-bbdc-d90a157a9e79">

on this video:
https://www.youtube.com/watch?v=k7YI3wmDVv8

Any idea why?

**Comment by DenBeke** [comment]
I tried updating yt-dlp, but to no avail, I get the same error also on my videos.

I currently have no idea about how to quickly fix it...

**Comment by bubio** [comment]
Hello!

This would have been fine.
https://github.com/yt-dlp/yt-dlp/releases/tag/2024.08.06

**Comment by DenBeke** [comment]
Yes, that solves the problem indeed. I think they just released it after I tested their newest release, because I hadn't seen that one yet.

Anyway: here is the newest release which solves the problem: https://github.com/DenBeke/YouTube-Downloader-for-macOS/releases/tag/v0.16

Enjoy!
