### ISSUE TITLE
fails a few times then works

### ISSUE THREAD

**Issue by frranck** [DenBeke/YouTube-Downloader-for-macOS#28]
Hello Mathias,
I have this transient bug happening, I need to try a couple of time before it actually downloads the video.
For example on https://www.youtube.com/watch?v=PwmTc5aGFbE
I got this error twice:
<img width="251" alt="Screenshot 2024-10-05 at 14 30 28" src="https://github.com/user-attachments/assets/bb0cbe7d-5df2-4652-a9ac-943e2205f622">
Then it worked, I'm having this behavior lately on pretty much all videos.
Cheers
Franck

**Comment by DenBeke** [comment]
Fixed in the latest release: https://github.com/DenBeke/YouTube-Downloader-for-macOS/releases/tag/v0.17 

Can you try again?

**Comment by frranck** [comment]
It seems to be fixed, thank you.
Btw, I noticed something else, it's behaving a bit strange when you try to download a live that is going on.

**Comment by DenBeke** [comment]
Never tried that actually 😉  
I suppose it goes on endlessly or something like that?

**Comment by frranck** [comment]
That happened this morning before my first coffee and I'm quite confused of what happened tbh. Seems like it grabbed a few seconds of the stream and then it switched to the live stream in my vlc.
