### ISSUE TITLE
Error on every video today

### ISSUE THREAD

**Issue by frranck** [DenBeke/YouTube-Downloader-for-macOS#31]
Hello Mathias,
Seems there's an error on every video this morning:
i.e https://www.youtube.com/watch?v=IUc0R8bbWQE
<img width="254" alt="Screenshot 2024-12-10 at 09 09 56" src="https://github.com/user-attachments/assets/438e209a-6664-4137-b28c-228653b2b612">
Cheers.

**Comment by HaydarJawad** [comment]
yes same here

**Comment by DenBeke** [comment]
I created a new release with the latest version of yt-dlp. Should fix your problems.

**Comment by frranck** [comment]
thanks you!
