### ISSUE TITLE
It just crashes when trying to download

### ISSUE THREAD

**Issue by bobrobot1** [DenBeke/YouTube-Downloader-for-macOS#4]
MacOS 10.13.6

**Comment by DenBeke** [comment]
Yeah, I never implemented error handling in this app. So probably Youtube changed something again.

I'll update it once I have the time.

**Comment by DenBeke** [comment]
Fixed in version 0.4: https://github.com/DenBeke/YouTube-Downloader-for-macOS/releases/tag/v0.4
