### ISSUE TITLE
Download Resolution?

### ISSUE THREAD

**Issue by erfgsthj** [DenBeke/YouTube-Downloader-for-macOS#5]
Hi! Thanks for fixing the crash error from before! You're awesome. Anyway, [This](https://www.youtube.com/watch?v=zCLOJ9j1k2Y) downloads at 720p, while [this](https://www.youtube.com/watch?v=dQw4w9WgXcQ) downloads at 360p! How do I pick a resolution? Thank you so so much!

**Comment by DenBeke** [comment]
It has probably to do something with the encoding. I opted for this app to not use any external dependencies, and thus it only downloads the highest resolutions that can be played on the Mac. (in an mp4 file).

I use the underlying tool [youtube-dl](https://youtube-dl.org) with the `-f mp4/best` command line argument.

If you want full control you can use youtube-dl on the command line and install ffmpeg (you can install both with [Homebrew](https://brew.sh)). This gives you full control and enables you to download in the highest possible resolution.

**Comment by Lord-V15** [comment]
@DenBeke Can you try removing **mp4** and just use `-f best` for the youtube-dl command ? 
I use `youtube-dl -f 'best'` and always get HD format (720p/1080p) but when I use YouTube-Downloader-for-macOS, I get 360p videos. 
Let me know if it's feasible for you to try !

**Comment by DenBeke** [comment]
I migrated from `youtube-dl` to `yt-dlp`. By doing those changes I also changed the command per your suggestions.
Downloads are now in 720 for everything I tested.
