### ISSUE TITLE
Nothing happens when I paste a YouTube link

### ISSUE THREAD

**Issue by glen4cindy** [DenBeke/YouTube-Downloader-for-macOS#6]
When I click on YouTube Downloader, I get the toolbar arrow.

When I click on that arrow and copy and paste the YouTube link into the box if I hit ENTER or DOWNLOAD, either one, I get a spinning icon but then nothing happens.

I have tried several YouTube links with the same results.

**Comment by DenBeke** [comment]
Could you send me a link that doesn't work for you? Because it seems to work here.

**Comment by glen4cindy** [comment]
One such link that I just tried is:  https://youtu.be/E2pAslx5az8

Here are the steps I took to use this. I went to the following link: https://github.com/DenBeke/YouTube-Downloader-for-macOS
Then I went to the Download section to Latest version and used the download link.

When I unzip the file I have a Youtube Downloader app that when I click on puts the down arrow in the toolbar. 

I did not run an "install" of anything. Did I miss a step to make this work properly?

Thanks for your help.

**Comment by DenBeke** [comment]
> Did I miss a step to make this work properly?

I missed the step of updating the readme :)
That link pointed to an older version.

Head over to the release page to download the latest version: https://github.com/DenBeke/YouTube-Downloader-for-macOS/releases

That should do the trick...

**Comment by DenBeke** [comment]
Feel free to reopen this issue if it didn't solve the problem.
