### ISSUE TITLE
Crashes when downloading.

### ISSUE THREAD

**Issue by bobrobot1** [DenBeke/YouTube-Downloader-for-macOS#7]
When I try to download a video ([this one](https://www.youtube.com/watch?v=dQw4w9WgXcQ)) it crashes.

**Comment by DenBeke** [comment]
I have fixed it in v0.5. https://github.com/DenBeke/YouTube-Downloader-for-macOS/releases/tag/v0.5

This should fix your problem.

**Comment by DenBeke** [comment]
Note: I also released v0.6 with a fix for the image thumbnail, so best to download that one immediately: https://github.com/DenBeke/YouTube-Downloader-for-macOS/releases/tag/v0.6
