### ISSUE TITLE
Not downloading video and crash (M1 MacBook Air)

### ISSUE THREAD

**Issue by TudorOnMac** [DenBeke/YouTube-Downloader-for-macOS#9]
When I put the link to a YouTube video, it just goes away from the menu bar and opens the Downloads folder with no video downoaded. Using the "untested" Apple Silicon version.

**Comment by TudorOnMac** [comment]
I tried making it compatible but it crashes at a `return info!` line.

<img width="1440" alt="Screenshot 2021-05-30 at 12 14 31" src="https://user-images.githubusercontent.com/78782971/120098882-0ec8ae80-c141-11eb-8580-65793560d920.png">

**Comment by TudorOnMac** [comment]
Not even Activity Monitor can close it nor the Terminal. Had to sign out.

**Comment by TudorOnMac** [comment]
Also it looks like when it tries to show what video am I trying to download it just fails.

**Comment by DenBeke** [comment]
Probably the version isn't compatible anymore with changes made on Youtube itself.  
I will update the binary to fix it.

**Comment by DenBeke** [comment]
Fixed in the [latest release (v0.8)](https://github.com/DenBeke/YouTube-Downloader-for-macOS/releases/tag/v0.8).

**Comment by TudorOnMac** [comment]
Amazing! Now it works. Thanks!
